### ISSUE TITLE
Implement a registry mechanism in maktaba for extending plugins

### ISSUE THREAD

**Issue by dbarnett** [google/vim-maktaba#130]
Some maktaba plugins like codefmt follow a modular design with a user interface and extensible functionality that can be provided by other plugins. The way maktaba models dependencies, this requires a library that serves as the registry/extension point and a plugin that provides the functionality, in addition to any actual plugins providing extensions. For instance, codefmtlib is an extremely simple library that currently defines three functions:

  * `codefmtlib#AddFormatter({formatter})`
  * `codefmtlib#AddDefaultFormatter({formatter})`
  * `codefmtlib#GetFormatters()`

We plan to continue making plugins extensible like this.

Rather than have two repositories per main plugin, we could abstract some kind of registry interface into maktaba so that codefmtlib and similar libraries would just be absorbed into maktaba. API TBD, but we could probably use the plugin name as (part of) a unique key, and the validation would be just configured when that plugin loads and validate existing entries retrospectively rather than being baked into the library.

**Comment by malcolmr** [comment]
Is the reason that we need two plugins because it's not possible to have a single plugin that's both a library and that provides UI functionality? (i.e. a hypothetical `codefmt-extras` can't depend upon `codefmt`, because the latter isn't a library plugin).  (And is that still a good design?)

I like this idea in general, though.

**Comment by dbarnett** [comment]
@Soares (who came up with the library/plugin distinction)

Correct. The rule is a little strong, but it is aimed squarely at bad design patterns I've seen in a lot of vim plugins in practice. OTOH, I still kind of circumvent it by declaring dependencies in addon-info.json for plugins like `codefmt-extras->codefmt` (since plugin managers don't care about what's a library). That should be more of a "Recommends" type dependency, which would be reasonable if such a thing were supported.

Anyway, the extension registry approach here wouldn't be the only way to solve the problem, but would probably be the most straightforward way to solve it.

**Comment by malcolmr** [comment]
Strawman API:

- `maktaba#extensions#RegisterExtensionClass({class}, {verifier})`
- `maktaba#extensions#AddExtension({class}, {extension})`
- `maktaba#extensions#GetExtensions({class})`

where:

-  `RegisterExtensionClass()` registers a new extension point, where `class` is a string describing the type of extension, typically named after the plugin that defines them (so, `codefmt`, or perhaps something like `codefmt:formatters` if you needed more that one class of extension per plugin), and `verifier` is a function that verifies that a given dict object is valid for the class. (i.e. the equivalent of `s:EnsureFormatter()` from codefmtlib).
- `AddExtension()` adds an extension dict to the end of the list for a given class and calls the verifier.
- `GetExtensions()` returns the extension dicts for the given class.

Note that this doesn't provide any mechanism for defaults. For `codefmt`, I'd imagine we'd add a `default` member to the existing formatter dict and use that to order the results.

One issue with this: I'm not sure whether we could always (usually?) ensure that `RegisterExtensionClass()` was called before `AddExtension()`, so we wouldn't necessarily be able to validate that a given class was known / a given extension dict was valid.  However, if it were usually the case that it was, then this is still useful.  (Perhaps `RegisterExtensionClass()` could verify any existing registrations and raise an error if any failed?)

**Comment by dbarnett** [comment]
Alternative proposal (typed half of this up before I saw Malcolm's response).

What I have in mind is that you can get a registry either from the PLUGIN object or a maktaba helper:
```
PLUGIN.GetRegistry() -> REGISTRY
maktaba#registry#Get({plugin_name}) -> REGISTRY
```
The one from the PLUGIN object is the plugin-internal interface and the helper is for access from other plugins.

It would have
```
REGISTRY.AddExtension({obj})
REGISTRY.GetExtensions() -> [extensions...]
REGISTRY.SetValidator({validator})
```
Objects added through the plugin-internal interface would be treated as "default" objects with lower precedence, equivalent to `codefmtlib#AddDefaultFormatter` above. (The interfaces would be the same type, just with a `._is_internal` boolean set on one to distinguish.)

GetExtensions and SetValidator would only need to work on the plugin-internal interface. SetValidator does two things:

  * Configures `{validator}` to be used on subsequent AddExtension calls.
  * Calls `{validator}` on each extension already registered.

Just copying codefmtlib into maktaba would get you halfway there.

**Comment by malcolmr** [comment]
Much nicer, though would we actually return a funcdict object with all three methods in both cases?

It seems like `maktaba#registry#Get()` could return one with just an `AddExtension()` method rather than a non-working implementation of `GetExtensions()` / `SetValidator()`.  (Unless I'm missing something about how Vim funcdicts work, which is completely possible.)

If we need the ability to have more than one registry per plugin, we can always add a qualifier to the `GetRegistry()` / `registry#Get()` calls later.

I do have a slight preference for `PLUGIN.GetExtensionRegistry()` / `maktaba#extension#GetRegistry()` (or `extensions`) rather than `maktaba#registry#Get()`, simply because 'registry' is such an overused term already (and to me implies something more like a place to store configuration settings).

**Comment by dbarnett** [comment]
> … though would we actually return a funcdict object with all three methods in both cases?

I just didn't want *two* new types that were slightly different. Plus they could fail with an error that says "only the plugin-internal interface can do that".

+1 for `PLUGIN.GetExtensionRegistry` and `maktaba#extension#GetRegistry`. I wasn't completely satisfied with my proposed names, either.

**Comment by malcolmr** [comment]
I've been trying to write a Vroom test for the above to prove the API. The only real questions I have so far are about registering extensions before the target plugin has been loaded:

- We've been thinking about the need to allow plugins to register extensions for other plugins that aren't yet loaded. However, if we discard the ability to register an extension for a plugin that we _never_ install, do we really need that? It seems like it would never be necessary for a plugin installing an extension to do so before it is loaded (i.e. `AddExtension()` shouldn't be called from `instant/`), and in that case, wouldn't we expect a plugin providing an extension point to call `SetValidator()` from `instant/extension.vim`, meaning that this situation would never occur in practice?

- Perhaps that only really applies to plugins loaded at vimrc time; would it be so bad for us to require that `codefmt` be installed before `codefmt-extras` is loaded?

- If we _do_ want to accept that model, what happens when an invalid extension is registered? As it stands, `GetExtensions()` would return it; throwing an error from `SetValidator()` and doing nothing (so that `GetExtensions()` still returns invalid extensions) seems unhelpful, but silently removing them from the list (while perhaps logging a failure) also doesn't seem particularly great.

- If we _don't_ need to allow pre-registration of extensions, should we consider a more explicit `PLUGIN.AddExtensionRegistry([validator])` that would allow us to fail-fast if a given plugin doesn't want to use extensions?

**Comment by dbarnett** [comment]
I'd rather not force plugins to use instant/ for anything they don't otherwise have to, or make any assumptions about the order of loading or how users will install plugins.

If an invalid extension is registered before the SetValidator call, SetValidator should shout an error and remove the offenders. We're emulating what would happen if the validator had been there all along, so I don't think it's that weird removing offenders from the list (but not silently, of course).

I'm hoping for issues like a typo in the plugin name we can detect when neither SetValidator nor GetExtensions was ever called and log a warning. That would also cover plugins that don't want to use extensions. The catch is how to determine "was never called": I'm not sure there's any non-hacky way to check late enough. If we can't, we could just make sure to log both the registration and first GetExtensions so you can cross-reference in the logs to find mismatches. This would be more a developer feature than a user feature, so logging is more appropriate than throwing errors, anyway.

**Comment by malcolmr** [comment]
Ah, I'd thought the install/loading order for Maktaba plugins was more constrained.

The "shout but don't fail" option was the one I was missing; that sounds ideal.

As to whether we can detect registrations against unknown plugins, I'm not sure, though I suspect not easily. Let's add logging for now; we should be able to improve things later.

**Comment by dbarnett** [comment]
Looks awesome, just the instant/ and throwing need updating (I decided both AddExtension and SetValidator should shout instead of propagating errors). Test-first development for vim plugins is pretty exciting to see. =)
