### ISSUE TITLE
Consider supporting vi compatible mode

### ISSUE THREAD

**Issue by dbarnett** [google/vim-maktaba#147]
The public Google vimscript styleguide says:
> Plugins that support vi compatibility mode must save and restore compatibility options as described in the Errata section so line continuations work properly.

But that's a moot point if maktaba errors out when installed under compatible mode since pretty much every Google vim plugin will depend on maktaba.

We should either fix maktaba to handle vi compatibility mode by saving/restoring options as needed or amend the style guide to stop recommending vi compatibility support.

**Comment by xanderman** [comment]
The style guide already strongly discourages supporting vi compatibility mode. If that's not clear enough, we should strengthen the claim. The line mentioned is included for completeness: If you're going to ignore our advice and support compatibility mode, at least do so correctly. That's why the actual save/restore method is in the errata instead of the main document.

**Comment by dbarnett** [comment]
BTW, I'm talking about the style guide at http://google-styleguide.googlecode.com/svn/trunk/vimscriptfull.xml. There's another version that's clear about not supporting it at Google, but the external version isn't so black and white.

After looking again, I suppose it's neutral-to-slightly-negative, and does explicitly mention maktaba doesn't support it.
