### ISSUE TITLE
Clarify usage of maktaba#library#Require in plugin files

### ISSUE THREAD

**Issue by glts** [google/vim-maktaba#148]
I'm having trouble understanding how to use `maktaba#library#Require`.

I'll try to put it in three bullet points.

First, it is unclear to me in which file the require statement belongs. If it goes in each plugin file (`commands.vim`, `plugs.vim`, `mappings.vim`, ...) and the requirement can't be met, the user will see the error message several times, once for each file. Is this working as intended?

Second, the docs aren't explicit about what the effect of a failed require is. Sourcing of the file continues even when a dependency is missing, and this will very probably result in a cascade of error messages. Perhaps the docs could point out that the boilerplate would typically look like this (?):

    if !maktaba#library#Require('firstlib')
      finish
    endif
    if !maktaba#library#Require('secondlib')
      finish
    endif
    ...

Third, some plugin files don't depend on a library directly, but they require the other plugin files which may depend on a library. `mappings.vim` for example, may be very lightweight and contain just this:

    let [s:plugin, s:enter] = maktaba#plugin#Enter(expand('<sfile>:p'))
    if !s:enter
      finish
    endif

    nnoremap <unique> cx <Plug>MappingInPlugsFileWithMissingDependency

If required dependencies haven't been met, the mapping will still be installed even though it will not be functional.

**Comment by dbarnett** [comment]
You're right, the docs don't explain usage very clearly. I'll give you the short version for now and also improve the docs to include this info.

The main purpose of `maktaba#library#Require` is to trigger an error if the library is missing. It should be used at the top of any file directly calling autoload functions from a library dependency, and generally that should only happen from autoload files in your plugin.

Any plugin dependencies should already be listed in your addon-info.json and are up to either users or the plugin manager to satisfy. These calls should more or less duplicate dependency information that's already declared, just declaring it at the file level.

You can also use `maktaba#library#AddInstaller` to configure makataba to install libraries on the fly when they're required instead of always shouting an error, but I don't think anyone really uses that yet.

Let me know if any of that is not clear or if you have any opinions about what the changes to the documentation should specifically include. I'll hopefully get those updated in the next few days.

**Comment by glts** [comment]
Thanks for your answer. So maktaba plugins assume that their dependencies *are* available, no compromise. `maktaba#library#Require` is only sort of a watch dog that's just there to notify the user that something is wrong with their setup - basically saying 'your config is broken, you must fix it right now'.

My three bullet points are all examples of not-so-graceful failure (repeated error messages, continuing sourcing with missing dependencies, non-functional mapping being installed). That's what bothered me enough to post here.

But if `maktaba#library#Require` doesn't need to fail more gracefully then that's fair I guess.

> You can also use `maktaba#library#AddInstaller` to configure makataba to install libraries on the fly when they're required instead of always shouting an error, but I don't think anyone really uses that yet.

I did play around with that (in fact [I am using it every day](https://github.com/glts/dotfiles/blob/4b8788663bf355a51b300938bcc0b89f51c0edbb/.vimrc#L10-L24)). I am still hoping for a plugin manager that integrates well with maktaba though, preferably one that can fetch dependencies from remote. Pity that there's still no established dependency management system with a central directory for Vim plugins. And `maktaba#library#Require` can't solve this problem by itself.

**Comment by dbarnett** [comment]
> So maktaba plugins assume that their dependencies are available …

Pretty much yeah. Actually, maktaba initially aimed to do more of the plugin manager work before we realized we should leave that to plugin managers. So there may be some misleading docs to be cleaned up for those library helpers.

> My three bullet points are all examples of not-so-graceful failure (repeated error messages, continuing sourcing with missing dependencies, non-functional mapping being installed).

It's at least partially intentional that it shouts an error message instead of throwing an error and halting execution, on the philosophy that thrown errors should pretty much never reach the user. They do add context to any subsequent errors you see. I don't see making mappings, commands, etc. conditional on whether the dependencies are satisfied. If anything, we'd just want to prevent the whole plugin from being loaded without its dependencies, but that too would fall on the plugin manager to make that work. As a user, your options are to figure out how to fix the plugin dependencies or remove it yourself until it's fixed. But IIRC, the errors also don't include any details about what plugin/file failed to have its dependencies loaded making it hard to troubleshoot.

> I am still hoping for a plugin manager that integrates well with maktaba though

[VAM](https://github.com/MarcWeber/vim-addon-manager) handles the dependencies, and there's been recent activity making Vundle handle them (gmarik/Vundle.vim#560).
