### ISSUE TITLE
Maktaba should use python for async calls if +python is available.

### ISSUE THREAD

**Issue by stgpetrovic** [google/vim-maktaba#150]
Maktaba can use python threads (limited by GIL but good for IO) if +python is available, and fallback on +clientserver.

**Comment by dbarnett** [comment]
+1. I thought you said vimscript callbacks from python threads didn't work or something, though.

**Comment by stgpetrovic** [comment]
I thought it was not possible, but I just learned that with certain conditions met, it works. If they are not met, it segfaults.

Even proper multithreading is possible if python extension in c++ is written (if we ever need that).

**Comment by dbarnett** [comment]
Yeah, I've seen segfault conditions. I think trying to update the buffer from a python thread does that? I'd want to make sure we can draw clear boundaries around this fallback (like supported vim versions) and make sure we're not making vim more crash-prone by making it frictionless for plugin developers to unintentionally do risky things.

**Comment by stgpetrovic** [comment]
So we need to be hacky and check the state of the thread on frequent events (CursorMoved), and if so, update the state from the vim thread. Doing anything from the python thread will segfault. I found this out by talking to Val and his work on ycm.

**Comment by dbarnett** [comment]
Some users disable CursorMoved or set it to really high values. Are you saying to make the maktaba implementation use CursorMoved or to require developers to use CursorMoved to handle their CallAsync results?

I would want to make sure that CallAsync usage was pretty much guaranteed not to hit segfault cases, since it would be very easy for developers to add CallAsync changes they didn't properly exercise and then start segfaulting users of their plugins.

**Comment by stgpetrovic** [comment]
I am not unconvinced we should do this if people do change the timeouts. We can detect them and fallback to +clientserver, though.

The suggestion is just to register a quick callback when CursorMoved happens to check if there are threads in python that have completed, and if so, we can do the callback from it. This needs to be in this main vim thread that calls to python, gets the results, and updates the state. If we would call it from the worker thread, it would segfault, so there are no segfaults here. Calling into python is very fast (Val says a few orders of magnitude than executing vimscript itself on the event), so it's cheap to do it often (and ycm does it apparently all the time, although I don't use it so I cant say what's the feeling).

**Comment by dbarnett** [comment]
Oh, I was confusing CursorMoved and CursorHold above.

So what you're suggesting is that if we detect python is available but clientserver/`v:servername` aren't, we would defer the callback handling to just the next time we check for events? But pbb still prefer clientserver if available since those callbacks are slightly more reliable?

There are one or two cases where I wanted to poll like this (detecting when no filetype was ever set and detecting when some settings like 'sw' change). There are some huge risks adding these kinds of workarounds into maktaba, though.

**Comment by dbarnett** [comment]
Closing in favor of #184 for vim and #125 for neovim. Ultimately I don't think we'll need python or clientserver implementations, just using the native jobs where available and optionally falling back to sync execution should give us pretty good polyfill coverage so people can write plugins that work great on new vim versions and still offer okay-ish support for older vim versions if needed.
