### ISSUE TITLE
vundle ask for github password when installing vim-maktaba

### ISSUE THREAD

**Issue by fmmirzaei** [google/vim-maktaba#160]
Trying to install maktaba with Vundle using

    Plugin 'gooole/vim-maktaba'

in my .vimrc and running `vim +PluginInstall +qall`, I'm asked for github password. No other vim plugin that I've installed through Vundle does that. (and I have ssh-key authentication, so github never asks for my password). It is likely that something is wrong with your github settings.

Can someone else please check this on their machine?

**Comment by dbarnett** [comment]
I've never heard of any problem like that and have no idea what configuration could be wrong. Maybe some setting on the github "google" team? I don't use Vundle but most other project members do… anyone else seen anything like this?

**Comment by malcolmr** [comment]
(I don't use Vundle either.) From what I understand, the GitHub google org is a little bit special in some respects, so I could believe that there might be a problem specific to it.

I think we need more information, though: is there some way to find out what commands Vundle is running for you, and get closer to the root cause?

**Comment by Kashomon** [comment]
I use Vundle and doing `:PluginInstall` works fine for me.

**Comment by fmmirzaei** [comment]
Sorry guys, there was a typo in the plugin name (en dash instead of
hyphen). Fixed it and works now.
