### ISSUE TITLE
GH run-tests actions failing for ubuntu-latest os (with error about missing impish Release file)

### ISSUE THREAD

**Issue by dbarnett** [google/vim-maktaba#253]
The test actions are failing at HEAD for the configurations using the ubuntu-latest os, with this error:
`E: The repository 'http://archive.ubuntu.com/ubuntu impish Release' does not have a Release file.`

It looks like since impish (20.10) wasn't an LTS release, it's already been removed from the ubuntu servers, so we can no longer use it to get testing packages. Should we now point that to "jammy" instead?

**Comment by dbarnett** [comment]
@snu5mumr1k any recommendations for updating the Ubuntu releases being used for this?

**Comment by snu5mumr1k** [comment]
Impish is 21.04 actually. That is controlled by [vim-from-testing](https://github.com/google/vim-maktaba/blob/master/.github/workflows/run-tests.yml#L16-L18).
I've added that to the config because the vim version from Debian testing wasn't available in the latest Ubuntu.

Now I'd just drop `vim-from-testing` altogether and add the new LTS (`ubuntu-22.04`) to the list of OS we test on.
