### ISSUE TITLE
Consider adding JSON support

### ISSUE THREAD

**Issue by dbarnett** [google/vim-maktaba#35]
In implementing addon-info.json introspection for maktaba, we had to pull some JSON parsing code into maktaba. We *might* want to move it into `maktaba#json` and expose it to maktaba users.

**Comment by malcolmr** [comment]
This would be very useful for google/vim-codefmt#13, where we need to parse the JSON response from `clang-format`.

What we could do is something like:
- if Vim is compiled with `+python` (not sure if we should consider `+python3`?), then use something based on `json.loads()` to parse the JSON directly using Vim's `:python` support.
- Otherwise, we shell out to something like `python -c "import json,sys;json.loads(sys.stdin.read())"` to validate that a given string _is_ JSON, then parse it with Vim's `eval()`.

If Python is actually not available at all, this would (currently) fail, but that's not that likely.

**Comment by dbarnett** [comment]
I like it!

We'll also want `pyeval()` support or #70.

When shelling out to python also consider which versions of python we support. (AFAICT that code snippet does support both py2 and py3).

**Comment by malcolmr** [comment]
I'm not sure we need to actually expose `maktaba#python#Eval()` as part of this, but you're right, we'll want a fallback, thanks.

(We could also consider whether `vim.bindeval()` is a good idea, since that appears to allow us to directly mutate a Vim Dictionary from within Python - but the fallback for that would be using `vim.eval()`, I think, which might be a bit tricky(?).)

**Comment by fowles** [comment]
@dbarnett I will trade you features.  If you give me this one I will implement https://github.com/google/vim-codefmt/issues/13 with it.

**Comment by dbarnett** [comment]
Haha, compelling offer…

Per https://github.com/VundleVim/Vundle.vim/pull/560#issuecomment-75502847, there are some security concerns with the way it's implemented that we'd need to revisit before exposing it as an API.

For google/vim-codefmt#13, you could probably put something in codefmt to say "if python support is available, use pyeval to read out cursor position, otherwise ignore the JSON and don't try to preserve cursor".

**Comment by malcolmr** [comment]
Partial implementation at https://github.com/google/vim-maktaba/compare/master...malcolmr:json, by the way. It mostly works with +python: IIRC, it's only missing a way to return JSON's `null`, `false`, and `true` (probably as sentinels with an optional variant that translates them to something like "", 0, 1).

It also needs a fallback for non-+python.

**Comment by dbarnett** [comment]
@malcolmr Awesome!

Re the fallback case, it occurs to me maktaba has a hard dep on addon-info.json, so any external deps for the fallback are external deps for maktaba as a whole. Could we hand-roll a custom serializer/deserializer that repeatedly regexes for quotes, commas, etc? It would not be efficient, but it's a fallback and only used for very small files.

**Comment by dbarnett** [comment]
I'm half finished with a pure vimscript implementation using your vroom tests. I say we wait for me to get that submitted, see how horribly slow it is, and if it helps you add your python implementation over it as an optimization.

**Comment by dbarnett** [comment]
Alright, now I can say I've written a recursive descent parser for JSON in vimscript. =)

@fowles Should be all set to use for your purposes (only invoked once per format on a tiny JSON blob, so the suboptimal performance shouldn't be an issue there). I bumped the version to 1.10.0, so you can either bump the `maktaba#IsAtLeastVersion()` check in codefmt's instant/flags.vim or have just the clang-format formatter complain it needs v1.10.0 if it gets an `E117: Unknown function`.

@malcolmr Should be all set to add your python implementation on top of it and send a pull req. To quickly check performance, I would recommend locally editing `maktaba#plugin#AddonInfo()` to use it and then timing vim startup with/without it using `time vim -c quit` (since it's used a bunch in vim startup). You can also try profiling it… fun but a little time-consuming (but python performance might not show up properly in profiling).

**Comment by malcolmr** [comment]
I think I'll need to test with larger documents to show a significant difference. Making maktaba#plugin#AddonInfo() call maktaba#json#Parse() costs me 6ms in startup, but I believe that's almost entirely due to having to find and load a new autoload file.

Python-based parsing _is_ (slightly) quicker than the Vimscript version for small documents (and it's probably more correct), but in my case (with only a very small number of plugins, since I'm at home), the one-time cost of initialising the Vim/Python environment means that the two end up being indistinguishable in practice, for a trivial `vim -c quit` test.

**Comment by dbarnett** [comment]
I pulled your changes and checked my startup time. Apparently my machine isn't so bogged down today, so I ran `stress` to try it out under some load. It does look like the python implementation has slightly better performance and isn't much worse than the EvalJSON regex hack we have now. Without `stress` the difference is even smaller.

Send a pull req and let's get a faster `maktaba#json#Parse`!

```
$ # EvalJSON hack
$ for x in {1..5}; do time vim -c quit; done
real  0m0.409s
user  0m0.279s
sys   0m0.046s

real  0m0.436s
user  0m0.318s
sys   0m0.021s

real  0m0.463s
user  0m0.294s
sys   0m0.041s

real  0m0.432s
user  0m0.282s
sys   0m0.034s

real  0m0.400s
user  0m0.276s
sys   0m0.044s
$ # JSON w/ python
$ for x in {1..5}; do time vim -c quit; done
real  0m0.481s
user  0m0.327s
sys   0m0.031s

real  0m0.437s
user  0m0.295s
sys   0m0.055s

real  0m0.548s
user  0m0.326s
sys   0m0.036s

real  0m0.485s
user  0m0.328s
sys   0m0.047s

real  0m0.480s
user  0m0.332s
sys   0m0.048s
$ # JSON no python
$ for x in {1..5}; do time vim -c quit; done
real  0m0.555s
user  0m0.371s
sys   0m0.053s

real  0m0.521s
user  0m0.376s
sys   0m0.031s

real  0m0.539s
user  0m0.378s
sys   0m0.029s

real  0m0.526s
user  0m0.375s
sys   0m0.048s

real  0m0.510s
user  0m0.377s
sys   0m0.026s
```

**Comment by malcolmr** [comment]
I need to make it pass the tests first :-)

**Comment by fowles** [comment]
Wow.  Way to force my hand :)

**Comment by dbarnett** [comment]
I went ahead and filed a request for native vim support: https://code.google.com/p/vim/issues/detail?id=383. If that ever lands, we can have a slightly better best-case performance. Then we could have two levels of fallback or consider getting rid of the intermediate python fallback.

**Comment by dbarnett** [comment]
Also, FYI, I found and fixed two bugs (empty dict and mixed-type lists): 31deca2a34
